# Generated by Django 4.2.19 on 2025-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Textbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("year", models.IntegerField()),
                ("edition", models.CharField(blank=True, max_length=50, null=True)),
                ("author", models.CharField(max_length=100)),
                ("course_code", models.CharField(max_length=9)),
                ("availabilty", models.BooleanField(default=True)),
            ],
        ),
    ]
