# Generated by Django 4.2.19 on 2025-03-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listtextbook", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="textbook",
            old_name="availabilty",
            new_name="availability",
        ),
    ]
