# Generated by Django 4.2.19 on 2025-03-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listtextbook", "0003_textbook_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textbook",
            name="condition",
            field=models.CharField(
                choices=[("new", "New"), ("old", "Old")], default="new", max_length=10
            ),
        ),
    ]
